[package]
name = "firefly-device"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"
wasmi = { version = "0.36.0", default-features = false }

# hosted
[target.'cfg(not(target_os = "none"))'.dependencies]
embedded-io = { version = "0.6.1", features = ["std"] }
gilrs = "0.10.6"

# web
[target.'cfg(target_family = "wasm")'.dependencies]
embedded-io = { version = "0.6.1", features = ["std"] }
gilrs = "0.10.6"
rust-embed = { version = "*", features = ["debug-embed"] }
vfs = { version = "*", features = ["embedded-fs"] }
wasm-bindgen = "*"
web-sys = { version = "0.3.69", features = ["Window", "Performance"] }

# embedded
[target.'cfg(target_os = "none")'.dependencies]
embedded-io = { version = "0.6.1", default-features = false }
