# https://taskfile.dev
version: "3"

tasks:
  run-host:
    internal: true
    cmds:
      - mv .cargo/config.toml .cargo/config.toml.bck
      - defer: mv .cargo/config.toml.bck .cargo/config.toml
      - cargo {{.COMMAND}}
  run-web:
    internal: true
    cmds:
      - mv .cargo/config.toml .cargo/config.toml.bck
      - defer: mv .cargo/config.toml.bck .cargo/config.toml
      - mv rust-toolchain.toml rust-toolchain.toml.bck
      - defer: mv rust-toolchain.toml.bck rust-toolchain.toml
      - cargo {{.COMMAND}} --target wasm32-unknown-unknown

  build-esp:
    - cargo build
  build-host:
    - task: run-host
      vars: { COMMAND: build }
  build-web:
    - task: run-web
      vars: { COMMAND: build }
  test-host:
    cmds:
      - task: run-host
        vars: { COMMAND: test }
  test:
    - task: build-esp
    - task: build-host
    - task: test-host

  lint-esp:
    cmds:
      - cargo clippy
  lint-host:
    cmds:
      - task: run-host
        vars: { COMMAND: clippy }
  lint:
    - task: lint-esp
    - task: lint-host

  all:
    cmds:
      - task: test
      - task: lint
