[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG = "INFO"

[build]
rustflags = [
  "-C",
  "link-args=-nostartfiles,-Wl,-Map=/home/gram/ff/firefly-supervisor/main.map",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
